export const PI = Math.PI;
export const TAU = 2 * PI;
const clamp = (x: number, min: number, max: number) => Math.max(Math.min(x, max), min);
export const sin = Math.sin;
export const cos = Math.cos;
export const sgn = Math.sign;
export const abs = Math.abs;
export const tan = (x: number) => clamp(Math.tan(x), -1, 1);
export const saw = (x: number) => 1 - (2 * x / TAU % 2 + 2) % 2;
export const tri = (x: number) => 1 - 4 * Math.abs(Math.round(x / TAU) - x / TAU);
export const noise3 = (x: number) => sin(x ** 3);
export const noise5 = (x: number) => sin(x ** 5);
